/*
 * BuiltInPacks.cpp
 * This file is part of Open-Typer
 *
 * Copyright (C) 2021-2022 - adazem009
 *
 * Open-Typer is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * Open-Typer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Open-Typer. If not, see <http://www.gnu.org/licenses/>.
 */

#include "BuiltInPacks.h"
#include <map>

namespace {
	static const QString autoGeneratedTr = QObject::tr("auto-generated");
	// Human-readable built-in pack names
	static const std::map<QString, QString> rawNameToFullName = {
		{ "sk_SK-QWERTZ-B1", "SK QWERTZ (ADK)" },
		{ "sk_SK-QWERTZ-A", "SK QWERTZ (" + autoGeneratedTr + ")" },
		{ "sk_SK-QWERTY-A", "SK QWERTY (" + autoGeneratedTr + ")" },
		{ "cs_CZ-QWERTZ-A", "CZ QWERTZ (" + autoGeneratedTr + ")" },
		{ "cs_CZ-QWERTY-A", "CZ QWERTY (" + autoGeneratedTr + ")" },
		{ "en_US-default-A", "EN (USA) (" + autoGeneratedTr + ")" },
		{ "de_DE-QWERTZ-A", "DE QWERTZ (DE) (" + autoGeneratedTr + ")" },
		{ "de_DE-QWERTY-A", "DE QWERTY (DE) (" + autoGeneratedTr + ")" },
	};
}

/*! Returns human-readable name of the built-in pack. */
const QString& BuiltInPacks::packName(QString rawName)
{
	if (const auto fullName = rawNameToFullName.find(rawName);
			fullName == rawNameToFullName.end())
	{
		static const QString unknownPackName = QObject::tr("Unknown pack");
		return unknownPackName;
	}
	else
	{
		return fullName->second;
	}
}
