/*
 * BuiltInPacks.cpp
 * This file is part of Open-Typer
 *
 * Copyright (C) 2021-2022 - adazem009
 * Copyright (C) 2022 - Roker2
 *
 * Open-Typer is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * Open-Typer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Open-Typer. If not, see <http://www.gnu.org/licenses/>.
 */

#include "BuiltInPacks.h"
#include <QMap>

namespace {
	static const QString autoGeneratedTr = QObject::tr("auto-generated");
	// Human-readable built-in pack names
	static const QMap<QString, QString> rawNameToFullName = {
		{ "sk_SK-QWERTZ-B1", "SK QWERTZ (ADK)" },
		{ "sk_SK-QWERTZ-A", "SK QWERTZ (" + autoGeneratedTr + ")" },
		{ "sk_SK-QWERTY-A", "SK QWERTY (" + autoGeneratedTr + ")" },
		{ "cs_CZ-QWERTZ-A", "CZ QWERTZ (" + autoGeneratedTr + ")" },
		{ "cs_CZ-QWERTY-A", "CZ QWERTY (" + autoGeneratedTr + ")" },
		{ "en_US-default-A", "EN (USA) (" + autoGeneratedTr + ")" },
		{ "de_DE-QWERTZ-A", "DE QWERTZ (DE) (" + autoGeneratedTr + ")" },
		{ "de_DE-QWERTY-A", "DE QWERTY (DE) (" + autoGeneratedTr + ")" },
	};
}

/*! Returns human-readable name of the built-in pack. */
QString BuiltInPacks::packName(QString rawName)
{
	if(!rawNameToFullName.contains(rawName))
	{
		static const QString unknownPackName = QObject::tr("Unknown pack");
		return unknownPackName;
	}
	else
	{
		return rawNameToFullName[rawName];
	}
}

/*! Returns list of supported keyboard layouts. */
QStringList BuiltInPacks::keyboardLayouts(void)
{
	QStringList out;
	QStringList keys = rawNameToFullName.keys();
	for(int i = 0; i < keys.size(); i++)
	{
		QString item = keyboardLayoutForPack(keys[i]);
		if(!out.contains(item))
			out += item;
	}
	out.sort();
	return out;
}

/*!
 * Returns list of packs for the given keyboard layout.\n
 * Returns all packs if keyboardLayout is empty.
 */
QStringList BuiltInPacks::packs(QString keyboardLayout)
{
	QStringList out;
	QStringList keys = rawNameToFullName.keys();
	if(keyboardLayout.isEmpty())
		return keys;
	for(int i = 0; i < keys.size(); i++)
	{
		if(keyboardLayoutForPack(keys[i]) == keyboardLayout)
			out += keys[i];
	}
	out.sort();
	return out;
}

/*! Returns the keyboard layout for this pack. */
QString BuiltInPacks::keyboardLayoutForPack(QString rawName)
{
	// Remove last word which usually looks like "(auto-generated)"
	QString value = rawNameToFullName[rawName];
	QStringList parts = value.split(" ");
	parts.removeAt(parts.length() - 1);
	return parts.join(" ");
}
