name: open-typer
description: |
  Open-Typer is a free and open source software for
  typewriting training and education. It runs on
  multiple operating systems.
base: core20
adopt-info: open-typer
confinement: strict

parts:
  open-typer:
    plugin: qmake
    parse-info: [../src/data/com.github.open-typer.open-typer.metainfo.xml]
    source: .
    source-type: git
    build-packages: [build-essential, qttools5-dev-tools, libssl-dev, libqt5charts5-dev, libqt5websockets5-dev]
    stage-packages: [libqt5gui5, libqt5widgets5, libqt5x11extras5, qtwayland5, libqt5charts5, libqt5websockets5, libqt5printsupport5, libqt5sql5, libqt5sql5-sqlite, libqt5svg5]
    override-pull: |
      snapcraftctl pull
      version=$(git describe --tags --abbrev=0 | sed 's/v//')
      snapcraftctl set-version "$version"
      snapcraftctl set-grade stable
    override-build: |
      QT_SELECT=qt5 lrelease ../src/*.pro
      snapcraftctl build
      ls
      ls ../src
      cp ../src/*.so* $SNAPCRAFT_PART_INSTALL/usr/lib/
      set -ex
    after: [desktop-qt5]

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18 and core20
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

apps:
  open-typer:
    common-id: com.github.open-typer.open-typer
    command: bin/desktop-launch open-typer
    plugs:
      - x11
      - unity7
      - network
      - network-bind
      - home
      - desktop
      - desktop-legacy
      - removable-media
      - opengl
      - cups-control
