/*
 * BuiltInPacks.h
 * This file is part of Open-Typer
 *
 * Copyright (C) 2021-2023 - adazem009
 * Copyright (C) 2022 - Roker2
 *
 * Open-Typer is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * Open-Typer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Open-Typer. If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef BUILTINPACKS_H
#define BUILTINPACKS_H

#if defined CORE_SHARED_LIB
#define CORE_LIB_EXPORT Q_DECL_EXPORT
#else
#define CORE_LIB_EXPORT Q_DECL_IMPORT
#endif

#include <QObject>
#include <QString>

/*! \brief The BuiltInPacks class provides functions for built-in pack settings. */
class CORE_LIB_EXPORT BuiltInPacks : public QObject
{
		Q_OBJECT
	public:
		Q_INVOKABLE static QString packName(QString rawName);
		Q_INVOKABLE static QStringList keyboardLayouts(void);
		Q_INVOKABLE static QStringList packs(QString keyboardLayout = "");
		Q_INVOKABLE static QString keyboardLayoutForPack(QString rawName);

	private:
		static QString autoGeneratedTr(void);
		static QMap<QString, QString> rawNameToFullNameMap(bool noAutoGenerated = false);
};

#endif // BUILTINPACKS_H
