name: Build

on:
  push:
    branches: '*'
    tags: '*'
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        qt-version: ['5.15.2']
        qt-target: ['desktop']
        include:
          - os: windows-latest
            qt-version: '5.15.2'
            qt-target: 'desktop'
            mingw-version: 81
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - name: Setup environment
      run: |
        sed -i -e '/^#/d' .github/config.env
        sed -i -e '/^$/d' .github/config.env
        cat .github/config.env >> "${GITHUB_ENV}"
      shell: bash
    - name: Get OS name
      run: |
        IFS='-'
        read -a arr <<< ${{ matrix.os }}
        echo "os_name=${arr[0]}" >> "${GITHUB_ENV}"
      shell: bash
    ## Install Qt
    # Windows
    - if: contains(matrix.os, 'windows')
      name: Install Qt (Windows)
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt-version }}
        host: 'windows'
        arch: 'win64_mingw${{ matrix.mingw-version }}'
        target: ${{ matrix.qt-target }}
        modules: 'qtcharts'
    - if: contains(matrix.os, 'windows')
      name: Install MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
    # MacOS
    - if: contains(matrix.os, 'macos')
      name: Install Qt (macOS)
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt-version }}
        host: 'mac'
        target: ${{ matrix.qt-target }}
        modules: 'qtcharts'
    ## Build
    - name: Build
      run: .ci/${{ env.os_name }}-build.sh
      shell: bash
    - if: contains(matrix.os, 'windows')
      name: Windows build
      run: |
        lrelease ${{ env.app_name }}.pro || exit 2
        qmake INCLUDEPATH+=C:\OpenSSL\include LIBS+=-LC:\OpenSSL\lib || exit 3
        mingw32-make -j4 || exit 4
        mkdir release
        move ${{ env.executable_name }}.exe release/
        move *.dll release/
        cd release
        windeployqt ${{ env.executable_name }}.exe --qmldir ..\app\ui\qml || exit 5
        windeployqt opentyper-core.dll || exit 5
      shell: cmd
    - if: contains(matrix.os, 'windows')
      name: Finalize Windows build
      run: .ci/${{ env.os_name }}-build.sh 1
      shell: bash
    ## Package
    # Windows
    - if: contains(matrix.os, 'windows')
      name: Package (Windows)
      uses: vimtor/action-zip@v1
      with:
        files: ../release/
        dest: ${{ env.app_name }}-win32.zip
    ## Upload
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-${{ env.os_name }}
        path: |
          ${{ env.executable_name }}
          *.zip
          *.AppImage
          *.dmg

  # WebAssembly
  wasm-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        qt-version: ['6.4.2']
        qt-target: ['desktop']
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    # Install emscripten
    - name: Install emscripten
      uses: mymindstorm/setup-emsdk@v11
      with:
        version: 3.1.14
        actions-cache-folder: 'emsdk-cache2'
    # Install Qt
    - name: Install desktop Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt-version }}
        aqtversion: '==3.1.0'
        py7zrversion: '==0.20.2'
        host: 'linux'
        arch: 'gcc_64'
        target: ${{ matrix.qt-target }}
        modules: 'qtcharts qt5compat qtshadertools'
        set-env: false
    - name: Install WASM Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt-version }}
        aqtversion: '==3.1.0'
        py7zrversion: '==0.20.2'
        host: 'linux'
        arch: 'wasm_32'
        target: ${{ matrix.qt-target }}
        modules: 'qtcharts qt5compat qtshadertools'
    # Build
    - run: source .ci/common/build.sh wasm
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: build-wasm
        path: |
          *.html
          *.js
          *.wasm
          *.svg
