name: Build

on:
  push:
    branches: [ master ]

jobs:
  # Linux
#  build-linux:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Qt - Linux
#      uses: jurplel/install-qt-action@v2
#      with:
#        version: '5.15.1'
#        host: 'linux'
#        target: 'desktop'
#        dir: '${{ github.workspace }}/build-linux/'
#        setup-python: 'false'
#    - name: Build - Linux
#      run: .ci/common/linux-build.sh $GITHUB_WORKSPACE
#    - uses: actions/checkout@v2
#      with:
#        ref: 'build'
#    - name: Commit - Linux
#      run: |
#        git config --local user.email "action@github.com"
#        git config --local user.name "GitHub"
#        mv /tmp/release/Open-Typer ./
#        git add Open-Typer
#        git commit -m "build: Linux"
#    - name: Push - Linux
#      uses: ad-m/github-push-action@master
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#        branch: build
  # Windows
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Qt - Windows
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.1'
        host: 'windows'
        target: 'desktop'
        arch: 'win32_mingw81'
        dir: '${{ github.workspace }}/build-windows/'
        setup-python: 'false'
        aqtversion: '>=0.9.0'
    - name: Build - Windows
      shell: bash
      run: .ci/common/linux-build.sh $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
      with:
        ref: 'build'
    - name: Commit - Windows
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub"
        mv /tmp/release/Open-Typer.exe ./
        git add Open-Typer.exe
        git commit -m "build: Windows"
    - name: Push - Windows
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: build
