name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Qt - Linux
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.8'
        host: 'linux'
        target: 'desktop'
        dir: '${{ github.workspace }}/build/'
        setup-python: 'false'
    - name: Build - Linux
      run: .ci/common/linux-build.sh $GITHUB_WORKSPACE
