name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Qt - Linux
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.8'
        host: 'linux'
        target: 'desktop'
        dir: '${{ github.workspace }}/build-data/'
        setup-python: 'false'
    - name: Build - Linux
      run: .ci/common/linux-build.sh $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
      with:
        ref: 'build'
    - run: |
      git config --local user.email "action@github.com"
      git config --local user.name "GitHub"
      git add Open-Typer
      git commit -m "build: Linux"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: build
