name: Build

on:
  push:
    branches: [ master ]

jobs:
  # Linux
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Qt - Linux
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.8'
        host: 'linux'
        target: 'desktop'
        dir: '${{ github.workspace }}/build-linux/'
        setup-python: 'false'
    - name: Build - Linux
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub"
        ./build-deb.sh
        mkdir -p ../build
        mv Open-Typer ../build/
        mv *.deb ../build/
    - uses: actions/checkout@v2
      with:
        ref: 'build'
    - name: Commit - Linux
      run: |
        rm *.deb
        mv ../build/Open-Typer ./
        mv ../build/*.deb ./
        git add -A
        git commit -m "build: Linux"
    - name: Push - Linux
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: build
  # Windows
  build-windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Qt - Windows
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.8'
        host: 'windows'
        target: 'desktop'
        arch: 'win32_mingw73'
        dir: '${{ github.workspace }}/build-windows/'
        setup-python: 'false'
        aqtversion: '>=0.9.0'
    - name: MinGW-w64
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: i686
    - name: Build - Windows
      run: |
        qmake
        C:\ProgramData\Chocolatey\lib\mingw\tools\install\mingw32\bin\mingw32-make.exe
        cd release
        windeployqt
        cd ..
      shell: cmd
    - uses: papeloto/action-zip@v1
      with:
        files: release/*.exe release/*.dll
        dest: ../Open-Typer-win32.zip
    - uses: actions/checkout@v2
      with:
        ref: 'build'
    - name: Commit - Windows
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub"
        rm -f Open-Typer-win32.zip
        mv ../Open-Typer-win32.zip ./
        git add Open-Typer-win32.zip
        git commit -m "build: Windows"
    - name: Push - Windows
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: build
  # MacOS
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Qt - MacOS
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.8'
        host: 'mac'
        target: 'desktop'
        dir: '${{ github.workspace }}/build-macos/'
        setup-python: 'false'
    - name: Build - MacOS
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub"
        qmake
        make -j$(nproc --all)
        mkdir -p ../build
        mv Open-Typer.app/Contents/MacOS/Open-Typer ../build/Open-Typer-mac
    - uses: actions/checkout@v2
      with:
        ref: 'build'
    - name: Commit - MacOS
      run: |
        mv ../build/Open-Typer-mac ./
        git add Open-Typer-mac
        git commit -m "build: MacOS"
    - name: Push - MacOS
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: build
