name: Build

on:
  push:
    branches: [ master ]

jobs:
  # Linux
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Qt - Linux
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.8'
        host: 'linux'
        target: 'desktop'
        dir: '${{ github.workspace }}/build-linux/'
        setup-python: 'false'
    - name: Build - Linux
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub"
        ./build-deb.sh
        mkdir -p ../build
        mv Open-Typer ../build/
        mv *.deb ../build/
    - uses: actions/upload-artifact@v2
      with:
        name: build-linux
        path: |
          ../build/Open-Typer*
          ../build/*.deb
  # Windows
  build-windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: OpenSSL
      run: |
        curl -o openssl.zip https://deac-fra.dl.sourceforge.net/project/openssl-for-windows/OpenSSL-1.1.1h_win32.zip
        mkdir C:\openssl
        unzip openssl.zip -d C:\openssl
        mv C:\openssl\OpenSSL-1.1.1h_win32 C:\openssl\lib
      shell: cmd
    - name: Qt - Windows
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win32_mingw81'
        dir: '${{ github.workspace }}/build-windows/'
        setup-python: 'false'
        aqtversion: '>=0.9.0'
    - name: MinGW-w64
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: i686
    - name: Build - Windows
      run: |
        qmake
        C:\ProgramData\Chocolatey\lib\mingw\tools\install\mingw32\bin\mingw32-make.exe
        cd release
        rm -f *.o *.cpp *.h
        windeployqt Open-Typer.exe
        cp C:\openssl\lib\libcrypto-1_1.dll .\
        cp C:\openssl\lib\libssl-1_1.dll .\
        cd ..
        mkdir ..\build
      shell: cmd
    - uses: papeloto/action-zip@v1
      with:
        files: release/
        dest: ../build/Open-Typer-win32.zip
    - uses: actions/upload-artifact@v2
      with:
        name: build-windows
        path: ../build/*.zip
  # MacOS
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Qt - MacOS
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.8'
        host: 'mac'
        target: 'desktop'
        dir: '${{ github.workspace }}/build-macos/'
        setup-python: 'false'
    - name: Build - MacOS
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub"
        qmake
        make -j$(nproc --all)
        mkdir ../build
    - uses: papeloto/action-zip@v1
      with:
        files: Open-Typer.app/
        dest: ../build/Open-Typer-macos.zip
    - uses: actions/upload-artifact@v2
      with:
        name: build-macos
        path: ../build/*.zip
