name: Linter

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
  push:
    branches: [master, staging]

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install clang-tools
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: 14
          directory: ${{ runner.temp }}/llvm
      - name: Install linter python package
        run: python3 -m pip install git+https://github.com/cpp-linter/cpp-linter-action@v1
      - name: Run linter
        id: linter
        run: cpp-linter --version=${{ runner.temp }}/llvm --style=file --ignore='.github|thirdparty' --tidy-checks='-*'

      - name: Fail
        if: steps.linter.outputs.checks-failed > 0
        run: |
          echo "Linting check failed!"
          exit 1
