name: Build Snap package

on:
  push:
    branches: '*'
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
        - amd64
        - armhf
        - arm64
        - ppc64el
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: docker/setup-qemu-action@v1
    - uses: diddlesnaps/snapcraft-multiarch-action@v1
      id: build
      with:
        architecture: ${{ matrix.arch }}
        snapcraft-args: '-v'
    - name: Upload the packages to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: snap
        path: ${{ steps.build.outputs.snap }}
    - if: startsWith(github.ref, 'refs/tags/v')
      name: Publish the package to the Snap Store
      uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_STORE_LOGIN }}
      with:
        snap: ${{ steps.build.outputs.snap }}
        release: stable
