name: Build Snap package

on:
  push:
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: 'Get Previous tag'
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@v1
    - run: sudo ln -s /var/snap/lxd/common/lxd /var/lib/lxd
      shell: bash
    - name: Install snapcraft
      uses: samuelmeuli/action-snapcraft@v1
      with:
        use_lxd: true
    - name: Build the Snap
      run: |
        VERSION=${{ steps.previoustag.outputs.tag }}
        VERSION=${VERSION//v}
        sed -i -e "s/<version>/${VERSION}/g" snap/snapcraft.yaml
        sg lxd -c 'snapcraft --use-lxd'
      shell: bash
    - name: Upload the package
      uses: actions/upload-artifact@v2
      with:
        name: snap
        path: '*.snap'
